### ISSUE TITLE
`npm start` fails on windows machines

### ISSUE THREAD

**Issue by leweaver** [WebVRRocks/webvrrocks#189]
Seems to be running linux specific commands in a script somewhere in "nunjucks" dependency:

> \> npm start
>
> \> webvrrocks@1.0.0 start C:\Users\xxx\repos\WebVR\webvrrocks 
> \> node dev.js
>
> C:\Users\xxx\repos\WebVR\webvrrocks\node_modules\.bin\nunjucks:2 
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> SyntaxError: missing ) after argument list
>    at Object.exports.runInThisContext (vm.js:76:16)
>    at Module._compile (module.js:542:28)
>    at Object.Module._extensions..js (module.js:579:10)
>    at Module.load (module.js:487:32)
>    at tryModuleLoad (module.js:446:12)
>    at Function.Module._load (module.js:438:3)
>    at Module.runMain (module.js:604:10)
>    at run (bootstrap_node.js:394:7)
>    at startup (bootstrap_node.js:149:9)
>    at bootstrap_node.js:509:3
> [0002] info  Server running at http://127.0.0.1:3000/ (connect)
> [0002] info  LiveReload running
> [0002] 242ms       34KB (browserify)

**Comment by cvan** [comment]
Will take a look at soon.
